library(ggplot2)
library(dplyr)
library(tidyr)
library(shiny)
library(shinydashboard)
library(stringr)
library(lubridate)
library(ggmap)
library(rgdal)
library(tmap)
library(plotly)
library(DT)
library(highcharter)
library(RColorBrewer)
library(rgeos)
library(leaflet)


calls = read.csv("311_calls.csv")
crime = read.csv("crime_clean1.csv")
crime2 = read.csv("crime_clean.csv")
shelter = read.csv("shelters.csv")
hc16 = read.csv("homeless2016tract.csv")
hc17 = read.csv("homeless2017final.csv")
la_map = get_map("Los Angeles County", zoom = 10)